### ISSUE TITLE
Project from template fails to run

### ISSUE THREAD

**Issue by Rek-Malorm** [futursolo/stackable#25]
Very interested in this template and gave it a go. Project generates, builds fine but on run crashes with the following.
Run: `cargo make start`
Output:
```
Built in 19.35s!
Stackable development server has started!


    Listening at: http://localhost:5000/


Note: This build is not optimised and should not be used in production.
To produce a production build, you can use `cargo make build`.
Error: No such file or directory (os error 2)
[cargo-make] ERROR - Error while executing command, exit code: 1
````

I did add --verbose to run but no additional output.
Is there a way to get a more verbose output or any dependency that may be missing?

Using Arch Linux with Linux 6.1,1-arch1-1 x86_64

Thank you

**Comment by futursolo** [comment]
Thank you for your interest!

For the development server to report it has started, it needs to be able to access `localhost:5000` at least once.
It is likely that the step to open the browser has failed.

By default, it opens the browser with `open` command and will fail if the system does not have open command installed.
You can confirm this with `which open`. If your system does not have the open command, you can remove `--open` from the start task in `Makefile.toml`.

**Comment by Rek-Malorm** [comment]
Perfect, that was exactly what caused my issue.
Thank you!
